apps/cars/pages/urls.py
from django.urls import path
from apps.cars.pages import views


urlpatterns = [
    path("", views.car_list_view, name="car_list_view"),
    path('<int:car_id>/', views.car_detail_view, name='car_detail_view'),
]

apps/reservations/pages/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('reserve/<int:car_id>/', views.reservation_create, name='reservation_create'),
    path('reservation/<int:reservation_id>/', views.reservation_detail, name='reservation_detail'),
    path('reservations/', views.reservation_list, name='reservation_list'),  # Esta ruta es la que corresponde a la vista reservation_list
]

service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.pages.urls')),  # Rutas de la app core
    path('auth/', include('apps.users.pages.urls', namespace='users')),  # Rutas de autenticación con namespace
    path('cars/', include('apps.cars.pages.urls')),  # Rutas de la app cars
    path('reservations/', include('apps.reservations.pages.urls')),  # Incluyendo las URLs de reservations
]

apps/cars/models.py
from django.db import models
from nanoid import generate  # Importa la función generate de la biblioteca nanoid

# Modelo para las marcas de autos
class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True)  # Nombre de la marca, único y con longitud máxima de 50 caracteres
    created_at = models.DateTimeField(auto_now_add=True)  # Fecha de creación, se establece automáticamente al crear
    updated_at = models.DateTimeField(auto_now=True)  # Fecha de última actualización, se actualiza automáticamente

    def __str__(self) -> str:
        return f"{self.name}"  # Devuelve el nombre de la marca al representarla como cadena

# Modelo para los modelos de autos
class CarModel(models.Model):
    # Campo único para identificar el modelo de auto, generado automáticamente y no editable
    hash = models.CharField(max_length=10, unique=True, editable=False, default=generate)    
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)  # Relación con la marca, si se elimina la marca, se eliminan los modelos asociados
    name = models.CharField(max_length=200)  # Nombre del modelo de auto, con longitud máxima de 200 caracteres
    created_at = models.DateTimeField(auto_now_add=True)  # Fecha de creación, se establece automáticamente al crear
    updated_at = models.DateTimeField(auto_now=True)  # Fecha de última actualización, se actualiza automáticamente

    def save(self, *args, **kwargs):
        # Si el campo hash no tiene valor (es decir, es una nueva instancia), genera un nuevo ID único
        if not self.hash:
            self.hash = generate(size=10)  # Genera un ID de 10 caracteres
        super().save(*args, **kwargs)  # Llama al método save() original para guardar la instancia

    def __str__(self) -> str:
        return f"{self.name}"  # Devuelve el nombre del modelo al representarlo como cadena

    class Meta:
        ordering = ['name']  # Ordena los modelos de autos por nombre de manera ascendente

# Modelo para los tipos de carrocería de los autos
class BodyType(models.Model):
    name = models.CharField(max_length=50, unique=True)  # Nombre del tipo de carrocería, único y con longitud máxima de 50 caracteres
    created_at = models.DateTimeField(auto_now_add=True)  # Fecha de creación, se establece automáticamente al crear
    updated_at = models.DateTimeField(auto_now=True)  # Fecha de última actualización, se actualiza automáticamente

    def __str__(self) -> str:
        return f"{self.name}"  # Devuelve el nombre del tipo de carrocería al representarlo como cadena

    class Meta:
        ordering = ['name']  # Ordena los tipos de carrocería por nombre de manera ascendente

# Modelo para representar un auto específico
class Car(models.Model):
    # Campo único para identificar el auto, generado automáticamente y no editable
    hash = models.CharField(max_length=10, unique=True, editable=False, default=generate)
    car_model = models.ForeignKey(CarModel, on_delete=models.CASCADE)  # Relación con el modelo de auto, si se elimina el modelo, se eliminan los autos asociados
    body_type = models.ForeignKey(BodyType, on_delete=models.CASCADE)  # Relación con el tipo de carrocería, si se elimina, se eliminan los autos asociados
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Precio del auto, con hasta 10 dígitos y 2 decimales
    engine_size = models.DecimalField(max_digits=10, decimal_places=1)  # Tamaño del motor, con hasta 10 dígitos y 1 decimal
    image_url = models.CharField(max_length=200)  # URL de la imagen del auto, con longitud máxima de 200 caracteres
    gearbox = models.CharField(max_length=50)  # Tipo de caja de cambios, con longitud máxima de 50 caracteres
    fuel_type = models.CharField(max_length=50)  # Tipo de combustible, con longitud máxima de 50 caracteres
    color = models.CharField(max_length=50)  # Color del auto, con longitud máxima de 50 caracteres
    year = models.PositiveIntegerField()  # Año de registro del auto
    mileage = models.PositiveIntegerField()  # Kilometraje del auto
    seats = models.PositiveIntegerField()  # Número de asientos en el auto
    doors = models.PositiveIntegerField()  # Número de puertas en el auto
    is_available = models.BooleanField(default=True)  # Indica si el auto está disponible, por defecto es True
    is_featured = models.BooleanField(default=False)  # Indica si el auto es destacado, por defecto es False
    created_at = models.DateTimeField(auto_now_add=True)  # Fecha de creación, se establece automáticamente al crear
    updated_at = models.DateTimeField(auto_now=True)  # Fecha de última actualización, se actualiza automáticamente

    def save(self, *args, **kwargs):
        # Si el campo hash no tiene valor (es decir, es una nueva instancia), genera un nuevo ID único
        if not self.hash:
            self.hash = generate(size=10)  # Genera un ID de 10 caracteres
        super().save(*args, **kwargs)  # Llama al método save() original para guardar la instancia

    def __str__(self):
        return f"{self.car_model.name} ({self.year})"  # Devuelve el nombre del modelo y el año del auto al representarlo como cadena

    class Meta:
        indexes = [
            models.Index(fields=['car_model']),  # Índice para el campo car_model, para mejorar las consultas
            models.Index(fields=['body_type']),  # Índice para el campo body_type, para mejorar las consultas
            models.Index(fields=['price']),  # Índice para el campo price, para mejorar las consultas
            models.Index(fields=['year']),  # Índice para el campo year, para mejorar las consultas
            models.Index(fields=['is_available']),  # Índice para el campo is_available, para mejorar las consultas
            models.Index(fields=['created_at']),  # Índice para el campo created_at, para mejorar las consultas
        ]
        
# Modelo para autos destacados
class FeaturedCar(models.Model):
    car = models.OneToOneField(Car, on_delete=models.CASCADE)  # Relación uno a uno con el modelo Car, si se elimina el auto, se elimina el destacado
    featured_date = models.DateTimeField(auto_now_add=True)  # Fecha en la que el auto fue destacado, se establece automáticamente
    updated_at = models.DateTimeField(auto_now=True)  # Fecha de última actualización del destacado, se actualiza automáticamente

    def __str__(self):
        return f"{self.car.car_model.name} ({self.car.year})"  # Devuelve el nombre del modelo y el año del auto destacado al representarlo como cadena

apps/cars/forms.py
from django import forms
from .models import Brand, CarModel  # Asegúrate de importar tus modelos

class CarFilterForm(forms.Form):
    brand = forms.ModelChoiceField(
        queryset=Brand.objects.all(), 
        required=False, 
        label="Marca",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    model = forms.ModelChoiceField(
        queryset=CarModel.objects.all(), 
        required=False, 
        label="Modelo",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    body_type = forms.ChoiceField(
        choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('coupe', 'Coupé'), ('hatchback', 'Hatchback')],
        required=False, 
        label="Tipo de Carrocería",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    year = forms.IntegerField(
        required=False, 
        label="Año", 
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    price_min = forms.DecimalField(
        required=False, 
        min_value=0, 
        label="Precio Mínimo", 
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    price_max = forms.DecimalField(
        required=False, 
        min_value=0, 
        label="Precio Máximo", 
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    fuel_type = forms.ChoiceField(
        choices=[('gasoline', 'Gasolina'), ('diesel', 'Diésel'), ('electric', 'Eléctrico')],
        required=False, 
        label="Tipo de Combustible",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    gearbox = forms.ChoiceField(
        choices=[('manual', 'Manual'), ('automatic', 'Automático')],
        required=False, 
        label="Transmisión",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    color = forms.CharField(
        max_length=50, 
        required=False, 
        label="Color",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

apps/cars/pages/views.py
from django.shortcuts import render, get_object_or_404
from apps.cars.models import Car
from apps.cars.forms import CarFilterForm

def car_list_view(request):
    cars = Car.objects.all()  # Obtiene todos los autos de la base de datos
    return render(request, 'cars/car_list.html', {'cars': cars})
    # Renderiza la plantilla con la lista de autos

def car_list_filter(request):
    form = CarFilterForm(request.GET or None)
    cars = Car.objects.all()

    if form.is_valid():
        if form.cleaned_data['brand']:
            cars = cars.filter(car_model__brand=form.cleaned_data['brand'])
        if form.cleaned_data['model']:
            cars = cars.filter(car_model=form.cleaned_data['model'])
        if form.cleaned_data['body_type']:
            cars = cars.filter(body_type=form.cleaned_data['body_type'])
        if form.cleaned_data['year']:
            cars = cars.filter(year=form.cleaned_data['year'])
        if form.cleaned_data['price_min']:
            cars = cars.filter(price__gte=form.cleaned_data['price_min'])
        if form.cleaned_data['price_max']:
            cars = cars.filter(price__lte=form.cleaned_data['price_max'])
        if form.cleaned_data['fuel_type']:
            cars = cars.filter(fuel_type=form.cleaned_data['fuel_type'])
        if form.cleaned_data['gearbox']:
            cars = cars.filter(gearbox=form.cleaned_data['gearbox'])
        if form.cleaned_data['color']:
            cars = cars.filter(color__icontains=form.cleaned_data['color'])

    return render(request, 'cars/car_list.html', {'form': form, 'cars': cars})

# Vista para mostrar los detalles de un auto específico
def car_detail_view(request, car_id):
    car = get_object_or_404(Car, id=car_id)  # Obtiene un auto específico o muestra un error 404 si no existe
    return render(request, 'cars/car_detail.html', {'car': car})  # Renderiza la plantilla con los detalles del auto

apps/cars/templates/cars/car_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<h1>{{ car.car_model.name }}</h1>
<img src="{{ car.image_url }}" alt="{{ car.car_model.name }} image">
<ul>
    <li><strong>Brand:</strong> {{ car.car_model.brand.name }}</li>
    <li><strong>Year:</strong> {{ car.year}} </li>
    <li><strong>Price:</strong> ${{ car.price }}</li>
    <li><strong>Engine Size:</strong> {{ car.engine_size }}L</li>
    <li><strong>Fuel Type:</strong> {{ car.fuel_type }}</li>
    <li><strong>Gearbox:</strong> {{ car.gearbox }}</li>
    <li><strong>Color:</strong> {{ car.color }}</li>
    <li><strong>Mileage:</strong> {{ car.mileage }} km</li>
    <li><strong>Seats:</strong> {{ car.seats }}</li>
    <li><strong>Doors:</strong> {{ car.doors }}</li>
    <li><strong>Body Type:</strong> {{ car.body_type.name }}</li>
    <li><strong>Availability:</strong>
        {% if car.is_available %}
        Available
        {% else %}
        Not Available
        {% endif %}
    </li>
    {% if car.is_featured %}
    <li><strong>Featured Car:</strong> Yes</li>
    {% endif %}
</ul>

<!-- Botón de reserva -->
{% if car.is_available %}
<a href="{% url 'reservations:reservation_create' car.id %}"
    class="btn btn-primary mt-3">Reserve</a>
{% else %}
<button class="btn btn-secondary mt-3" disabled>Not Available for
    Reservation</button>
{% endif %}

<a href="{% url 'car_list_view' %}" class="btn btn-link mt-3">Back to Car
    List</a>
{% endblock content %}

apps/cars/templates/cars/car_list.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}

<form method="GET">
    <div class="form-group">
        {{ form.brand.label_tag }} {{ form.brand }}
    </div>
    <div class="form-group">
        {{ form.model.label_tag }} {{ form.model }}
    </div>
    <div class="form-group">
        {{ form.body_type.label_tag }} {{ form.body_type }}
    </div>
    <div class="form-group">
        {{ form.year.label_tag }} {{ form.year }}
    </div>
    <div class="form-group">
        {{ form.price_min.label_tag }} {{ form.price_min }}
    </div>
    <div class="form-group">
        {{ form.price_max.label_tag }} {{ form.price_max }}
    </div>
    <div class="form-group">
        {{ form.fuel_type.label_tag }} {{ form.fuel_type }}
    </div>
    <div class="form-group">
        {{ form.gearbox.label_tag }} {{ form.gearbox }}
    </div>
    <div class="form-group">
        {{ form.color.label_tag }} {{ form.color }}
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
</form>

<h1>Available Cars</h1>
<div class="row row-cols-1 row-cols-md-2 g-4">
    {% for car in cars %}
    <div class="col">
        <div class="card">
            <img src="{{ car.image_url }}" class="card-img-top"
                alt="{{ car.car_model.name }}">
            <div class="card-body">
                <h5 class="card-title">
                    {{ car.car_model.name }} {{ car.year }}
                </h5>
                <p class="card-text">
                    <strong>Brand:</strong> {{ car.car_model.brand.name }}<br>
                    <strong>Price:</strong> ${{ car.price }}<br>
                    <strong>Engine Size:</strong> {{ car.engine_size }}L<br>
                    <strong>Fuel Type:</strong> {{ car.fuel_type }}<br>
                    <strong>Gearbox:</strong> {{ car.gearbox }}<br>
                    <strong>Color:</strong> {{ car.color }}
                </p>
                <a href="{% url 'car_detail_view' car_id=car.id %}"
                    class="btn btn-primary">View Details</a>
            </div>
        </div>
    </div>
    {% empty %}
    <p>No cars available.</p>
    {% endfor %}
</div>
{% endblock content %}